name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "Weather Processing/requirements.txt"

    - name: Run pylint
      run: |
        pylint --fail-under=8.0 "Weather Processing/*.py" > pylint_recommendations.txt
      working-directory: ${{ github.workspace }}
      continue-on-error: true

    - name: Overwrite linting recommendations in README
      run: |
        awk '/Here are the linting recommendations/{print; system("cat pylint_recommendations.txt"); exit} 1' README.md > README.md.tmp
        mv README.md.tmp README.md
      working-directory: ${{ github.workspace }}
      continue-on-error: true

    - name: Print final README
      run: cat README.md
      working-directory: ${{ github.workspace }}
      continue-on-error: true
